# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8fc6ca4b97ec042625b570c65263720e1d40ad2e148f14726c711a315aa7a7a8d8b9760a3204fda5b89d2184ec6ab0819e3ccaeb13664a4ef52ef905097d4f

test:
  secret_key_base: 2bbb9347178cd14e3269f380d3b56a026747d06f16984c5445b536e027f3ae5897be3aa5027e506175c549ef753da379ea54a4a1389943f75303c2ee9347ecea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
